# Generated by Django 5.1.3 on 2024-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_coffee_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
